version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: laravel5x-redis

  db:
    image: mysql:5.7
    container_name: laravel5x-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel5x
    
  myadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db
    ports: 
      - "3000:80"
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on: 
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel5x-webserver
    working_dir: /application
    volumes:
        - ./src:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    depends_on: 
      - db
      - myadmin

  php-fpm:
    build: phpdocker/php-fpm
    container_name: laravel5x-php-fpm
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on: 
      - webserver
  

